---
- name: Kubernetes Pod Resource Usage Report
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    report_directory: "c:\n8n\reports"

  tasks:
    - name: Ensure reports directory exists
      ansible.windows.win_file:
        path: "{{ report_directory }}"
        state: directory

    - name: Run Kubernetes authentication script
      script: c:\n8n\kube444_taskrunner.py
      register: auth_result

    - name: Verify Kubernetes authentication
      debug:
        msg: "Authentication result: {{ auth_result.stdout }}"

    - name: Execute custom script for gathering pod metrics
      script: c:\n8n\custom_metrics_gatherer.py
      register: metrics_result

    - name: Display metrics results
      debug:
        var: metrics_result.stdout_lines

